add technical committee
bids-standard/bids-extensions pull request #29
Opened 2024-02-26 16:14 UTC by CPernet

Following the steering group committee meeting 22 February 2024, a request to the technical committee should be  done if consensus can't be reached

2024-02-26 16:18 UTC, CPernet commented
@yarikoptic @arokem @cmaumet @dorahermes as discussed

2024-02-26 16:20 UTC, CPernet commented
can't assign reviewers?? @Remi-Gau @effigies thx

2024-02-26 16:36 UTC, Remi-Gau commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
OK with the rule that steering group and maintainer help with the decision making but 
I am going to be annoying. Isn't it easier to to just say:

> you can ask the BIDS steering group and maintainers to to take a decision

than introducing a new "name" that appears no where else (OK I may be wrong on this one) and then define it

we already suffer from "jargonitis", I don't think we need more terms. 😜

2024-02-26 17:15 UTC, CPernet commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
that's how 'people' referred to it but yes I agree -- shouldn't be the advisory group instead?

2024-02-26 17:19 UTC, oesteban commented
These changes raise more questions than they resolve.

Currently, the governance states:

> Upon a successful Draft BEP review, the BEP will be converted from a google document to a markdown file and entered as a pull request on the [BIDS standard](https://github.com/bids-standard/bids-specification). This will enable further community feedback on the Proposed BEP. Tools may begin integrating the Proposed BEP specification.
>
> The criteria for merging a Proposed BEP into the BIDS Standard:
> 
> 1. Proposal positively reviewed by representative community members. The definition of “representative” will differ depending on the scope of the extension and will be reviewed as part of the steering group’s final approval.
> 2. BIDS Steering Group final approval.

This is particularly unclear regarding when a proposal can be deemed as *positively reviewed by representative community members*, because it doesn't clarify when that review happens. My interpretation is that *reviewed* here is linked to 'pull-request review', so I interpret that this is applicable in the last PR phase.

The changes make the interpretation of the governance harder: how exactly should *If alternative proposals are made among members and no consensus is reached* be interpreted? By the looks of the current governance, the procedure is that the proposal must be positively reviewed by representative community members. IMHO, this wants to preempt BEPs from being accepted (PR merged) unless those *representative community members* deliver a positive review (of the PR, on GitHub). When an *alternative proposal* becomes an alternative and to which point is just the *due discussion over a particular BEP aspect*? 

Then the *you can ask the technical committe to take a decision (BIDS steering group + maintainers)* phrasing is really problematic. First, who is *you*? When this mechanism can be triggered? Can it be triggered before the BEP reaches the PR phase?

However, the most worrying aspect to me is the spirit. This seems intended to shut down conversation and overrule opposing views rather than promote consensus.

Finally, if this is the outcome of the idea to unlock BEP038 that I shared with some *representative community members* two weeks ago, it doesn't address the issues I raised regarding the transparency of the BEP discussion and how the BEP lifecycle could be improved.

2024-02-26 17:27 UTC, CPernet commented
the sterring group decided that the bep leads decide when stuck -- I will add this info

2024-02-26 17:33 UTC, Remi-Gau commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
"advisory group" in the governance is composed of the ex-BEP leaders (leaders of the BEP that were merged) so that name is taken

Signed: pedantic Rémi. 😉

2024-02-26 17:44 UTC, yarikoptic commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
Let's try to avoid coming up with a new term ATM and make it explicit:

```suggestion
   multiple iterations of the draft. 
   If alternative proposals are made among members and no consensus is reached, you can ask the joint of BIDS steering group and BIDS maintainers group to make a decision.
```

? Longer term (more proper?): Looking at https://bids.neuroimaging.io/governance.html#3-leadership-structure
![image](https://github.com/bids-standard/bids-extensions/assets/39889/9567193f-5405-448e-9260-2716968a6f6d)
we
- talk in terms of "Groups", not committees
- we could introduce some "Arbitrage Group" or "Technical Resolution Group" as dashed rectangle over "Steering" and "Maintainers" Groups there. 

What would be the contact point -- just a joint of the two groups somehow, but how -- an issue with `@bids-standard/steering` and `@bids-standard/maintainers`  ? or we should not bother describing that ?

2024-02-26 17:50 UTC, CPernet commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
I'm happy whatever -- but if we can avoid a new name, it's better ... 'add-hoc arbitrage group from the steering and maintainer groups' ?

2024-02-26 18:32 UTC, oesteban requested changes
This seems to reflect a recent decision of the Steering Committee. It is difficult to gauge how representative this is of the decision at this point (see, e.g., https://github.com/bids-standard/bids-extensions/pull/29#issuecomment-1964708397 which may or may not answer some of my questions above).

The decision is apparently made, so I can only voice my concern about the spirit of what this PR seems to implement and its potential use to replace consensus with expert opinion. It is unclear how the "decisors" will handle conflicts of interest (e.g., being already part of the conversation, or developing activities that could directly be affected by the decision).

On the other hand, the letter of the decision (this PR) falls very short in contextualizing the proposal within current governance and guidelines.

2024-02-26 18:32 UTC, oesteban commented on docs/assets/img/bep_process.png
This flowchart should include the [key definitions of the BEP procedure](https://bids.neuroimaging.io/governance.html#a-bep-procedure-key-definitions)

- It is unclear in the flowchart when the BEP reaches the "Proposed BEP" status,
- is that "first complete draft of the extension with examples" a Draft BEP or a Proposed BEP?
- when a Proposed BEP becomes a PR?

2024-02-26 18:32 UTC, oesteban commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
```suggestion
9. Incorporate the feedback and strive for consensus.
  This may involve multiple iterations of the draft.
  If alternative proposals are made among members and no consensus is reached, the BEP Working Group can ask the technical committee (BIDS steering group + maintainers) to make a decision.
```

- Please use semantic line breaks
- Typos
- Who is intended to trigger this mechanism? The BEP working group? (before the discussion of who makes the decision)
- How it is decided that *no consensus is reached*? For how long must the conversation be open to allow feedback to come in?
- How will BIDS make discussions accessible to minorities and community members who cannot attend BEP organization calls (e.g., because of time zone) or in-person workshops (because only *representative members of the community* are invited or because of lack of resources or ethical traveling restrictions)?

2024-02-26 21:06 UTC, yarikoptic commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
something like that. May be quantify it as `ad-hoc arbitrage group which must contain at least 50% of representatives from the steering and 50% of representatives from maintainer groups` ?

2024-02-26 21:12 UTC, yarikoptic commented on docs/assets/img/bep_process.png
all of that IMHO is outside the scope of this PR, which is  the clarification on how to deal with a "stale mate" situation and being unable to proceed forward.  So let's address 1 item at a time.

FWIW, for the background -- one of the examples I used to support such proposal is https://www.debian.org/devel/tech-ctte to which Debian project getting referred to in similar cases

2024-02-26 21:16 UTC, oesteban commented
I agree it's out of the scope, but this PR is not applicable if those
problems are not addressed first.

So, either that is addressed in a different PR that gets merged before this
one or else it's addressed within this one.

Otherwise it's adding obscurity to something already unclear.

On Mon, Feb 26, 2024, 22:12 Yaroslav Halchenko ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On docs/assets/img/bep_process.png
> <https://github.com/bids-standard/bids-extensions/pull/29#discussion_r1503305370>
> :
>
> all of that IMHO is outside the scope of this PR, which is the
> clarification on how to deal with a "stale mate" situation and being unable
> to proceed forward. So let's address 1 item at a time.
>
> FWIW, for the background -- one of the examples I used to support such
> proposal is https://www.debian.org/devel/tech-ctte to which Debian
> project getting referred to in similar cases
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bids-standard/bids-extensions/pull/29#discussion_r1503305370>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAESDRXMGWSB3RHRC4OBZTLYVT3DPAVCNFSM6AAAAABD2PXAYCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBSGAZDCNZRHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-02-26 21:19 UTC, yarikoptic commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
+1 on semantic libe breaks and not typos (we have codespell bolted on, don't we ?) ;)

for the rest let's try  with a tune up to your suggestion

```suggestion
9. Incorporate the feedback and strive for consensus.
  This may involve multiple iterations of the draft.
  If alternative proposals are made among members and no consensus is reached by BEP leads, a BEP lead can ask BIDS steering group to compose an ad-hoc decision group (consisting of at least 50% of members from each of the Steering and Maintainers groups) to review the case and to make a decision.
```

while omitting any temporal considerations: IMHO would be too much at this point/in general.
Delegating responsibility to BEP leads IMHO addresses concerns about other BEP members and their availability.

2024-02-27 06:29 UTC, oesteban commented on docs/assets/img/bep_process.png
Unfortunately, email responses don't get properly threaded. I'm moving my response 9h ago in here:

> I agree it's out of the scope, but this PR is not applicable if those
> problems are not addressed first.
> 
> So, either that is addressed in a different PR that gets merged before this
> one, or else it's addressed within this one.
> 
> Otherwise, it's adding obscurity to something already unclear.

2024-02-27 18:32 UTC, sappelhoff commented on docs/assets/img/bep_process.png
I agree with Oscar that before we are introducing new groups/processes/etc. we should first clarify and formalize the existing ones, along the lines of what is intended with:

- https://github.com/bids-standard/bids-extensions/pull/28

2024-02-27 18:36 UTC, sappelhoff commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
> we have codespell bolted on, don't we ?

on the bids-specification repository, yes. On this repo we don't have any CIs switched on (yet).

2024-02-28 08:28 UTC, Remi-Gau commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
I can take care of that if you want.

2024-02-28 09:55 UTC, CPernet commented
updated - thx for feedback

2024-02-28 10:33 UTC, Remi-Gau commented on docs/guide.md
> +   multiple iterations of the draft. If alternative proposals are made among members and no consensus is reached, you can ask the technical committe to take a decision (BIDS steering group + maintain
minimal formatting, spell check now implemented via pre-commit, codespell, pre-commit ci

2024-02-28 13:39 UTC, yarikoptic commented on docs/assets/img/bep_process.png
My 1c: https://bids.neuroimaging.io/governance.html#bids-steering-group already says

"**The BIDS Steering Group is responsible for approving and advancing BEPs through the BIDS standard process,**"

IMHO indeed we should review the governance document and actually reduce number of detailed technical aspects in it, e.g. such ones as 

"The Steering Group evaluates: ... Validator updated to include the Proposed BEP specification ..."

since in the landscape of changing technologies they would keep constantly changing (e.g. now it would require review of schema changes more than validator changes which ideally should not happen at all as a result of a BEP IMHO). Governance document should describe responsibilities of different groups, their composition (elections), and interactions between them, and to not detail their operational procedures (how often to meet, how to approve/advice etc). E.g. we should probably add there clearly that Steering group has responsibility and power to adjust operational procedures for "advancing BEPs through the BIDS standard process", which is the document here.

Overall, IMHO this document edited here is/should be the main document with the details for "advancing BEPs through the BIDS standard process" which "BIDS Steering Group is responsible for".  I do not think all the details should be duplicated into governance document, and they were not in full so far, so I do not think that this particular aspect should be duplicated there.

2024-02-28 13:48 UTC, CPernet commented on docs/assets/img/bep_process.png
do you want to open a separate issue for this - and we can revise it at the next meeting?

2024-03-31 07:07 UTC, CPernet commented
why has this moved to draft? this was changes decided by the steering groups and conflicts above were resolved @sappelhoff

2024-03-31 08:27 UTC, oesteban commented
> this was changes decided by the steering groups

This is incorrect. At most, this may try to reflect decisions by the SG, but it cannot be "changes decided by" because of the simple fact that it is written after the meeting happened, as far as I understand.

There is a great deal of difference between the SG voting on a set of specific changes (i.e., they are written beforehand) and the SG voting on something, and someone then takes care of putting that into writing (which I believe is what happened here).

IMHO (and as expressed in my comments) these changes open more questions than they respond and it would be irresponsible to merge the PR as it is. I also think the SG should decide on a concrete proposal (i.e., revert the workflow described above -- first write the proposal and have the SG vote on the specific changes).

2024-03-31 08:44 UTC, CPernet commented
This is a PR reflecting change in the process, which falls under the 'general decisions regarding the standard'. It was discussed by SG to improve that part of the process (along with another PR running along side with one).  Nothing wrong before/after.

I addressed the specific issues raised above. There is nothing I can do about the general comment (people who do not like what an elected group decide should themselves go on being elected). Unless a specific issue that conflicts with the general process, we should move forward.

2024-03-31 09:31 UTC, oesteban commented
The SG could not issue a nuanced decision because there was no specific set of changes being proposed. If the SG had made the decision on a specific proposal already commented by the community I would agree the PR would be implementing such a decision.

> There is nothing I can do about the general comment

I disagree. My comments warn about negative aspects of these particular changes. As an SG member you should reconsider this and strive for consensus instead of push it without considering.

> (people who do not like what an elected group decides should themselves go on being elected)

This is a dangerous view: running to the SG should be a generous decision with the intent of helping BIDS forward instead of a way of passing personal agendas.

In addition, some people run for SG and do not get elected. Some people don't feel they will be able to serve and give BIDS time or guarantee they will act unbiased and they do not run for it.

2024-03-31 21:38 UTC, sappelhoff commented
> why has this moved to draft? this was changes decided by the steering groups and conflicts above were resolved @sappelhoff

Based on all posts until here, I was under the impression that this specific proposal (and/or the process in which it is brought forward) needs further discussion before it can be merged, as it seems to be surprising to some.

That's why I converted it to "draft" (and would recommend to do so again).

cc @bids-standard/steering @bids-standard/maintainers

2024-06-21 09:58 UTC, Remi-Gau commented
Note that most if not all of this repo will be transferred to the new BIDS website:
- bids website repo: https://github.com/bids-standard/bids-website/tree/main
- pages from the bids-extension repo as rendered in the website: https://bids-website.readthedocs.io/en/latest/extensions/docs/index.html

If the move is confirmed / community approved, I would suggest closing this PR.

2024-06-21 10:10 UTC, closed without merging